/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kevin
 */
public class Game extends javax.swing.JInternalFrame {

    /**
     * Creates new form Game
     */
    int count;
    public Game() {
        initComponents();
        count=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Q1 = new javax.swing.JLabel();
        A2 = new javax.swing.JTextField();
        Q2 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        Q3 = new javax.swing.JLabel();
        A3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JLabel();
        Q5 = new javax.swing.JLabel();
        A4 = new javax.swing.JTextField();
        A5 = new javax.swing.JTextField();
        first = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lost = new javax.swing.JLabel();
        Win = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        w3 = new javax.swing.JLabel();
        w4 = new javax.swing.JLabel();
        w5 = new javax.swing.JLabel();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1350, 600));
        setRequestFocusEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JButton(), org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("closable"));
        bindingGroup.addBinding(binding);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        Q1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q1.setText("Q1. Which is the most efficent Scheduling Algorithm ?");
        getContentPane().add(Q1);
        Q1.setBounds(110, 100, 310, 30);

        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        A2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A2KeyPressed(evt);
            }
        });
        getContentPane().add(A2);
        A2.setBounds(110, 200, 270, 30);

        Q2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setText("Q2. Who won the 2014 Fifa Wolrd Club ?");
        getContentPane().add(Q2);
        Q2.setBounds(110, 170, 320, 30);

        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        A1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A1KeyPressed(evt);
            }
        });
        getContentPane().add(A1);
        A1.setBounds(110, 130, 270, 30);

        Q3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q3.setForeground(new java.awt.Color(255, 255, 255));
        Q3.setText("Q3. Which year did India win the 60-over world cup ?");
        getContentPane().add(Q3);
        Q3.setBounds(110, 240, 300, 30);

        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        A3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A3KeyPressed(evt);
            }
        });
        getContentPane().add(A3);
        A3.setBounds(110, 270, 270, 30);

        Q4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q4.setForeground(new java.awt.Color(255, 255, 255));
        Q4.setText("Q4. What is the highest individual score in an ODI match ?");
        getContentPane().add(Q4);
        Q4.setBounds(110, 310, 310, 30);

        Q5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Q5.setForeground(new java.awt.Color(255, 255, 255));
        Q5.setText("Q5. Who is the first person to step on moon ?");
        getContentPane().add(Q5);
        Q5.setBounds(110, 380, 270, 30);

        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        A4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A4KeyPressed(evt);
            }
        });
        getContentPane().add(A4);
        A4.setBounds(110, 340, 270, 30);

        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        A5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                A5KeyPressed(evt);
            }
        });
        getContentPane().add(A5);
        A5.setBounds(110, 410, 270, 30);

        first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newhang1.png"))); // NOI18N
        getContentPane().add(first);
        first.setBounds(930, 150, 240, 390);

        second.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newhang2.png"))); // NOI18N
        second.setText("               ");
        getContentPane().add(second);
        second.setBounds(810, 140, 160, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newlive.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(820, 250, 130, 190);

        Lost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newdead.png"))); // NOI18N
        getContentPane().add(Lost);
        Lost.setBounds(820, 250, 130, 190);

        Win.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newlive.png"))); // NOI18N
        getContentPane().add(Win);
        Win.setBounds(820, 250, 130, 190);

        w1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrng.png"))); // NOI18N
        w1.setText("Wrong");
        getContentPane().add(w1);
        w1.setBounds(440, 120, 37, 48);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        c2.setText("Correct");
        getContentPane().add(c2);
        c2.setBounds(440, 190, 37, 48);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        c3.setText("Correct");
        c3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        getContentPane().add(c3);
        c3.setBounds(440, 260, 37, 50);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        c4.setText("Correct");
        c4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        getContentPane().add(c4);
        c4.setBounds(440, 330, 37, 48);

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        c5.setText("Correct");
        getContentPane().add(c5);
        c5.setBounds(440, 400, 37, 48);

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crct.png"))); // NOI18N
        c1.setText("Correct");
        getContentPane().add(c1);
        c1.setBounds(440, 120, 37, 48);

        w2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrng.png"))); // NOI18N
        w2.setText("Wrong");
        getContentPane().add(w2);
        w2.setBounds(440, 190, 37, 48);

        w3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrng.png"))); // NOI18N
        w3.setText("Wrong");
        getContentPane().add(w3);
        w3.setBounds(440, 260, 37, 48);

        w4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrng.png"))); // NOI18N
        w4.setText("Wrong");
        getContentPane().add(w4);
        w4.setBounds(440, 330, 37, 48);

        w5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrng.png"))); // NOI18N
        w5.setText("Wrong");
        getContentPane().add(w5);
        w5.setBounds(440, 400, 37, 48);

        s1.setText("Submit");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(520, 130, 90, 23);

        s2.setText("Submit");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2);
        s2.setBounds(520, 200, 90, 23);

        s3.setText("Submit");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        getContentPane().add(s3);
        s3.setBounds(520, 270, 90, 23);

        s4.setText("Submit");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        getContentPane().add(s4);
        s4.setBounds(520, 350, 90, 23);

        s5.setText("Submit");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        getContentPane().add(s5);
        s5.setBounds(520, 420, 90, 23);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retry.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 170, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1370, 600);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A2KeyPressed
        /*       // TODO add your handling code here:
        if(A2.getText().equals("Germany"))
        {
            c2.setVisible(true);
            Q3.setVisible(false);
            A3.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w2.setVisible(true);
                Q3.setVisible(false);
                A3.setVisible(true);
                first.setVisible(true);
                count++;
            }
            else
            {
                w2.setVisible(true);
                Q3.setVisible(false);
                A3.setVisible(true);
                second.setVisible(true);
                count++;
            }
        }*/
    }//GEN-LAST:event_A2KeyPressed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A1KeyPressed
        /*        // TODO add your handling code here:
        if(A1.getText().equals("six"))
        {
            c1.setVisible(true);
            Q2.setVisible(true);
            A2.setVisible(true);
        }
        else
        {
            w1.setVisible(true);
            Q2.setVisible(true);
            A2.setVisible(true);
            first.setVisible(true);
            count++;

        }*/

    }//GEN-LAST:event_A1KeyPressed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A3KeyPressed
        // TODO add your handling code here:
        /*      if(A3.getText().equals("1983"))
        {
            c3.setVisible(true);
            Q4.setVisible(false);
            A4.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w3.setVisible(true);
                Q4.setVisible(false);
                A4.setVisible(true);
                first.setVisible(true);
                count++;
            }
            else if(count==1)
            {
                w3.setVisible(true);
                Q4.setVisible(false);
                A4.setVisible(true);
                second.setVisible(true);
                count++;
            }
            else
            {
                w3.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                count++;
            }
        }*/
    }//GEN-LAST:event_A3KeyPressed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A4KeyPressed
        // TODO add your handling code here:
        /*        if(A4.getText().equals("264"))
        {
            c4.setVisible(true);
            Q5.setVisible(false);
            A5.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w4.setVisible(true);
                Q5.setVisible(false);
                A5.setVisible(true);
                first.setVisible(true);
                count++;
            }
            else if(count==1)
            {
                w4.setVisible(true);
                Q5.setVisible(false);
                A5.setVisible(true);
                second.setVisible(true);
                count++;
            }
            else
            {
                w4.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                count++;
            }
        }    */
    }//GEN-LAST:event_A4KeyPressed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void A5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A5KeyPressed
        /*      // TODO add your handling code here:
        if(A5.getText().equals("Neil Armstrong"))
        {
            c5.setVisible(true);
            Win.setVisible(true);
            //    Q5.setVisible(false);
            //    A5.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w5.setVisible(true);
                //    Q5.setVisible(false);
                //    A5.setVisible(true);
                first.setVisible(true);
                Win.setVisible(true);
                count++;
            }
            else if(count==1)
            {
                w4.setVisible(true);
                //        Q5.setVisible(false);
                //        A5.setVisible(true);
                Win.setVisible(true);
                second.setVisible(true);
                count++;
            }
            else
            {
                w4.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                count++;
            }
        }  */
    }//GEN-LAST:event_A5KeyPressed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        if(A1.getText().equals("SRTF"))
        {
            c1.setVisible(true);
            Q2.setVisible(true);
            A2.setVisible(true);
        }
        else
        {
            w1.setVisible(true);
            Q2.setVisible(true);
            A2.setVisible(true);
            first.setVisible(true);
            count++;

        }
                s2.setVisible(true);
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        if(A2.getText().equals("Germany"))
        {
            c2.setVisible(true);
            Q3.setVisible(true);
            A3.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w2.setVisible(true);
                Q3.setVisible(true);
                A3.setVisible(true);
                first.setVisible(true);
                count++;
            }
            else
            {
                w2.setVisible(true);
                Q3.setVisible(true);
                A3.setVisible(true);
                second.setVisible(true);
                count++;
            }
        }
        s3.setVisible(true);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
        if(A3.getText().equals("1983"))
        {
            c3.setVisible(true);
            Q4.setVisible(true);
            A4.setVisible(true);
            s4.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w3.setVisible(true);
                Q4.setVisible(true);
                A4.setVisible(true);
                first.setVisible(true);
                s4.setVisible(true);
                count++;
            }
            else if(count==1)
            {
                w3.setVisible(true);
                Q4.setVisible(true);
                A4.setVisible(true);
                second.setVisible(true);
                s4.setVisible(true);
                count++;
            }
            else
            {
                w3.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                jLabel4.setVisible(false);
                count++;
            }
            
        }
        
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
        if(A4.getText().equals("264"))
        {
            c4.setVisible(true);
            Q5.setVisible(true);
            A5.setVisible(true);
            s5.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w4.setVisible(true);
                Q5.setVisible(true);
                A5.setVisible(true);
                first.setVisible(true);
                count++;
                s5.setVisible(true);
            }
            else if(count==1)
            {
                w4.setVisible(true);
                Q5.setVisible(true);
                A5.setVisible(true);
                second.setVisible(true);
                count++;
                s5.setVisible(true);
            }
            else
            {
                w4.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                jLabel4.setVisible(false);
                count++;
            }
        }
        
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
        if(A5.getText().equals("Neil Armstrong"))
        {
            c5.setVisible(true);
            Win.setVisible(true);
            jLabel4.setVisible(false);
            //    Q5.setVisible(false);
            //    A5.setVisible(true);
        }
        else
        {
            if(count==0)
            {
                w5.setVisible(true);
                //    Q5.setVisible(false);
                //    A5.setVisible(true);
                first.setVisible(true);
                Win.setVisible(true);
                jLabel4.setVisible(false);
                count++;
            }
            else if(count==1)
            {
                w4.setVisible(true);
                //        Q5.setVisible(false);
                //        A5.setVisible(true);
                Win.setVisible(true);
                second.setVisible(true);
                jLabel4.setVisible(false);
                count++;
            }
            else
            {
                w4.setVisible(true);
                //    Q4.setVisible(false);
                //    A4.setVisible(true);
                Lost.setVisible(true);
                jLabel4.setVisible(false);
                count++;
            }
        }
    }//GEN-LAST:event_s5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
   
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        home.jComboBox1.removeItem("Game");
    }//GEN-LAST:event_formInternalFrameClosed

    void reset()
    {
        second.setVisible(false);
        first.setVisible(false);
        Win.setVisible(false);
        Lost.setVisible(false);
        
        Q2.setVisible(false);
        Q3.setVisible(false);
        Q4.setVisible(false);
        Q5.setVisible(false);
        
        A2.setVisible(false);
        A3.setVisible(false);
        A4.setVisible(false);
        A5.setVisible(false);
        
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        
        w1.setVisible(false);
        w2.setVisible(false);
        w3.setVisible(false);
        w4.setVisible(false);
        w5.setVisible(false);
        
        s2.setVisible(false);
        s3.setVisible(false);
        s4.setVisible(false);
        s5.setVisible(false);
    
        A1.setText("");
        jLabel4.setVisible(true);
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField A4;
    private javax.swing.JTextField A5;
    private javax.swing.JLabel Lost;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Win;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel first;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JLabel second;
    private javax.swing.JLabel w1;
    private javax.swing.JLabel w2;
    private javax.swing.JLabel w3;
    private javax.swing.JLabel w4;
    private javax.swing.JLabel w5;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
